version: "3.0"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IS_DEVELOPMENT: 1
    networks:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./src:/user/app/src
      - ./tests:/user/app/tests

networks:
  api:
